version: '2'
services:
  spring-petclinic-rest-owner:
    image: 730329488449.dkr.ecr.us-west-2.amazonaws.com/spring-petclinic-rest-owner
    build:
      context: .
    cpu_shares: 100
    mem_limit: 524288000
    ports:
      - "9084:8080"